### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by bigtiger** [bustlelabs/shep#43]
Running through the Readme the first time I came across this error:

``` bash
Unhandled rejection TimeoutError: Missing credentials in config
    at ClientRequest.<anonymous> (/Users/jim/.nvm/versions/node/v4.0.0/lib/node_modules/shep/node_modules/aws-sdk/lib/http/node.js:56:34)
    at ClientRequest.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at ClientRequest.emit (events.js:166:7)
    at Socket.emitTimeout (_http_client.js:534:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:318:8)
    at _runOnTimeout (timers.js:512:11)
    at _makeTimerTimeout (timers.js:503:3)
    at Timer.unrefTimeout (timers.js:572:5)
```

There's a required step to set up AWS credentials as explained in the document [Configuring the SDK in node.js](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html).

**Comment by southpolesteve** [comment]
@bigtiger thanks for the feedback! I added some info to the readme in https://github.com/bustlelabs/shep/pull/47 about configuring the AWS credentials.

**Comment by jagthedrummer** [comment]
I just ran into this same problem, but I have `~/.aws/credentials` set up with two different profiles. Other AWS tools are finding those credentials just fine, so I'm fairly sure that I have it configured correctly. Any ideas?

**Comment by jagthedrummer** [comment]
Ah-ha! The problem seems to be that I had two named profiles, but no 'default' profile. When I added one named 'default' it started working.
